# Generated by Django 3.2.8 on 2021-10-08 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_channel_name', models.CharField(max_length=255, null=True, unique=True)),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_thread', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_thread', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Threads',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipient_message', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='my_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_for_thread', to='chat_control.threads')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
